//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReversePolish.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReversePolish.Resources.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Formula to convert:.
        /// </summary>
        internal static string Enter_Formula_to_convert {
            get {
                return ResourceManager.GetString("Enter_Formula_to_convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Formula.
        /// </summary>
        internal static string Invalid_Formula {
            get {
                return ResourceManager.GetString("Invalid_Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching left parenthesis, please fix and try again..
        /// </summary>
        internal static string No_matching_left_parenthesis_please_fix_and_try_again {
            get {
                return ResourceManager.GetString("No_matching_left_parenthesis_please_fix_and_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching right parenthesis, please fix and try again..
        /// </summary>
        internal static string No_matching_right_parenthesis_please_fix_and_try_again {
            get {
                return ResourceManager.GetString("No_matching_right_parenthesis_please_fix_and_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result: {0}.
        /// </summary>
        internal static string Result_PARM {
            get {
                return ResourceManager.GetString("Result_PARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string Something_went_wrong {
            get {
                return ResourceManager.GetString("Something_went_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong {0}.
        /// </summary>
        internal static string Something_went_wrong_PARAM {
            get {
                return ResourceManager.GetString("Something_went_wrong_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Error.
        /// </summary>
        internal static string Syntax_Error {
            get {
                return ResourceManager.GetString("Syntax_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Symbol {0}, Please Remove..
        /// </summary>
        internal static string Unknown_Symbol_PARAM_Please_Remove {
            get {
                return ResourceManager.GetString("Unknown_Symbol_PARAM_Please_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you have entered is invalid, Please try again..
        /// </summary>
        internal static string What_you_have_entered_is_invalid_please_try_again {
            get {
                return ResourceManager.GetString("What_you_have_entered_is_invalid_please_try_again", resourceCulture);
            }
        }
    }
}
